name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    needs: [extension, ubuntu]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

  extension:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn workspace @iron/extension install
      - run: yarn workspace @iron/extension build:zip

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./extension/extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip

  ubuntu:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies (ubuntu only)
        run: |
          echo {{matrix.platform}}
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - run: yarn workspace @iron/gui install

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/release/iron
          asset_name: iron-ubuntu-x86_64
          asset_content_type: application/octet-stream
